name: Build and push Docker image
on:
  workflow_call:
    outputs:
      image:
        description: "Docker image URI"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    permissions:
      actions: read # for sarif
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      # - name: Cache Dependencies
      #   uses: actions/cache@v6
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-maven-
      # - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
      #   with:
      #     java-version: 25
      #     distribution: temurin
      #     cache: maven
      # - name: Build & package
      #   run: mvn -B package
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@8e41f1f58749b9248e376c25d33bfbdd2b1163c0
        id: docker-push
        with:
          team: sikkerhetstjenesten
          pull: true
          byosbom: target/classes/META-INF/sbom/application.cdx.json
      # - name: Generate and submit dependency graph
      #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2
        with:
          sarif_file: 'trivy.sarif'

