name: Build and deploy main
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-build-deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    uses: ./.github/workflows/build-and-push.yml
  deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: test-build-deploy
    strategy:
      matrix:
        cluster: [dev-gcp]
    name: Deploy to ${{ matrix.cluster }}
    environment: ${{ matrix.cluster }}:sikkerhetstjenesten
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      # Duplicated build steps from build-and-push, for troubleshooting only
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: '11'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
      - run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run build
      # End duplicated build steps
      - uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # Deploy
        env:
          PRINT_PAYLOAD: true
          RESOURCE: .nais/naiserator.yaml
          CLUSTER: ${{ matrix.cluster }}
          VARS: .nais/${{matrix.cluster}}.json
          IMAGE: ${{ needs.test-build-deploy.outputs.image }}
