name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      actions: read
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    needs: build
    strategy:
      matrix:
        cluster: [dev-gcp, prod-gcp]
    name: Deploy to ${{ matrix.cluster }}
    environment: ${{ matrix.cluster }}:sikkerhetstjenesten
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@7ad7c2b833e1db74a80954e3ee6bb6ac060a8ae7 # v2
        env:
          PRINT_PAYLOAD: true
          RESOURCE: .nais/naiserator.yaml
          CLUSTER: ${{ matrix.cluster }}
          VARS: .nais/${{ matrix.cluster }}.json
          IMAGE: ${{ needs.build.outputs.image }}
